
name: fetch new letters from reddit

on:
    schedule:
        - cron: '0 5 * * *'

jobs:
    get-letters:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.12'
                cache: 'pip' # caching pip dependencies
            - run: pip install -r requirements.txt
            - run: python get_letters.py
            - uses: stefanzweifel/git-auto-commit-action@v5