
name: fetch new letters from reddit

on:
    schedule:
        - cron: '0 5 * * *'
    workflow_dispatch:

jobs:
    get-letters:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.12'
                cache: 'pip'
            - run: pip install -r requirements.txt
            - run: python get_letters.py
              env: 
                reddit_secret: ${{secrets.REDDIT_SECRET}}
            - uses: stefanzweifel/git-auto-commit-action@v5